### ISSUE TITLE
Python error on utils/generate_miniapp.py

### ISSUE THREAD

**Issue by petermcLBL** [ECP-WarpX/picsar#12]
I am trying to generate the PICSARlite miniapp following the instructions, with: `python  utils/generate_miniapp.py`

When using Python 2.7, I get `ERROR: missing end module block statement`

When using Python 3.4 or 3.6, I get `SyntaxError: Missing parentheses in call to 'print'`
I can change occurrences of `print "string"` to `print('string')` and try again, but still get `ERROR: missing end module block statement` and the only subdirectory of `PICSARlite` that's generated is `src`.

**Comment by jlvay** [comment]
Hi Peter.  We are not using PICSAR’s PIC routines in WarpX anymore and are thus not maintaining  the PICSARlite mini app.

Let’s discuss how we can set something up for you, using the latest version of WarpX.

**Comment by petermcLBL** [comment]
Hi Jean-Luc,

Yes, we could use a new WarpX miniapp.  Would there be a way to do
this without AMReX?  We are looking for a miniapp that does not
require AMReX, or other libraries, but everything in WarpX now uses
AMReX data structures, doesn't it?

Peter

**Comment by jlvay** [comment]
You are correct. WarpX uses AMReX data structures right now, thus there is no path at this point for putting together a WarpX miniapp that does not use AMReX.
